import type { Metadata } from "next";
import { Poppins } from "next/font/google"; //Change if you want to use a different font from Google Fonts
import "./globals.css";
import Navbar from "@/components/Navbar";

const mainFont = Poppins({
  //Change if you want to use a different font from Google Fonts
  variable: "--font-main",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], //Change if you want to use different font weights from Google Fonts
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mainFont.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col p-px">
        <Navbar className="fixed top-0 inset-x-0 z-50 h-24 bg-black" />
        <main className="flex-1 pt-24">{children}</main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
